server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    try_files /index.html =404;
  }

  location = /install.sh {
    types { }
    default_type text/plain;
    charset utf-8;
    try_files /scripts/install.sh =404;
  }

  location = /install-zh.sh {
    types { }
    default_type text/plain;
    charset utf-8;
    try_files /scripts/install-zh.sh =404;
  }

  location = /install.ps1 {
    types { }
    default_type text/plain;
    charset utf-8;
    try_files /scripts/install.ps1 =404;
  }

  location = /install-zh.ps1 {
    types { }
    default_type text/plain;
    charset utf-8;
    try_files /scripts/install-zh.ps1 =404;
  }

  location /assets/ {
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
